# fly.toml app configuration file generated for 2020tech-admin on 2024-11-19T13:35:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '2020tech-admin'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
